#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

#Check Root
[ $(id -u) != "0" ] && { echo "Error: You must be root to run this script"; exit 1; }

rm -rf /usr/local/caddy/Caddyfile
echo ":80 {
 basicauth / $1 $2
 proxy / http://127.0.0.1:8000
}" > /usr/local/caddy/Caddyfile
service caddy restart
echo "修改成功！"
